### PR TITLE
Wire spec version 2

### PR DESCRIPTION
**Pull request by rachmatowicz**
Draft version of the wire-spec-v2.
A wire spec does not get into implementation details, so I have tried to give an overall descrption of what the protocol is trying to do and any additional request response data required.

### CODE REVIEW

**Review by ropalka — APPROVED** [review]

**Comment by ropalka** [comment]
I just managed to review the diff between v1 & v2 documents. All looks good to me @rachmatowicz .

**Comment by rachmatowicz** [comment]
I need to add the discovery operation wire spec. This was also omitted from v1.

**Comment by ropalka** [comment]
Reviewed also Discovery request / response amendment. Still LGTM.

**Comment by rachmatowicz** [comment]
I've made the final updates to this document. I tried to harmonize the content of the sections, and added the interoperability headers into the protocol descriptions.

**Comment by ropalka** [comment]
Reviewed also after the final update of the document - LGTM.

**Comment by rachmatowicz** [comment]
Just realigned a few fields with no changes to content.

**Comment by rachmatowicz** [comment]
I have updated the document to remove references to the x-wf-version header which is only used in v1 messages and and added an explaatory note in the changes since v1 section. This can be merged as I won't be making any further changes.

**Review by fl4via — APPROVED** [review]

**Comment by ropalka** [comment]
Thanks @rachmatowicz !

**Pull request merged**
