### PR TITLE
[WEJBHTTP-57] Use error code and initCause of XAException

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/WEJBHTTP-57

@fl4via @ropalka @ochaloup would anyone please review? thanks :)

### CODE REVIEW

**Review by ropalka — COMMENTED** [review]
I see three places in HttpRemoteTransactionPeer @gaol where XAException is intantiated.
Shouldn't all three places be implemented in the same way?

**Comment by gaol** [comment]
@ropalka thanks for the review, and good catch :) 

Yes, I see another one in [HttpRemoteTransactionPeer#recover()](https://github.com/wildfly/wildfly-http-client/blob/c235adae2352509ad3f6a184904e37316901786a/transaction/src/main/java/org/wildfly/httpclient/transaction/HttpRemoteTransactionPeer.java#L133), this XAException is thrown when it failed to recover the transaction, which error code should be used for this case? @ochaloup

**Comment by ochaloup** [comment]
@gaol The same `RMFAIL` makes sense for `recover` as well. The `RMFAIL` means that the RM is currently not available but it can be available in the next recovery attempt (the recovery is run periodically by background thread, trying to finish in-doubt transactions).
(I can just note that from Narayana perspective the error code for `recover` does not matter as any exception is handled the same. from XA spec the `RMFAIL` makes the most sense to me)

**Comment by gaol** [comment]
@ochaloup thanks, I updated the PR to use `RMFAIL` error code for the three XAException initialization. @ropalka would you please review again? thanks :)

**Review by ochaloup — APPROVED** [review]

**Review by ropalka — APPROVED** [review]

**Pull request merged**
