### PR TITLE
[WEJBHTTP-35] HttpEJBDiscoveryProvider: per-invocation outstandingCount

### PR DESCRIPTION
**Pull request by tadamski**
@ropalka This fixes the regression in the testsuite. 

OTOH we should decide whether we move the discovery to another branch
(@darranl  FYI)

### CODE REVIEW

**Comment by ropalka** [comment]
@fl4via  started merging it into master @tadamski  - I will continue this way.

**Comment by darranl** [comment]
TBH you would generally keep the features going into master anyway, if something is needed for maintenance releases without adding new features the general approach is to add a new branch for those.

**Comment by tadamski** [comment]
Maybe I would revert all the changes then and create another PR for 1.1 (?) branch?

**Comment by darranl** [comment]
I don't think many repositories would use their master branch as a maintenance branch with a named branch as their feature branch - normally master branches are used for the latest releases with named branches used for maintenance of older minors and majors.

**Comment by ropalka** [comment]
I created 1.0 branch (where I reverted all EJB over HTTP discovery commits)
and in master we have 1.1 branch ATM where new feature is present.
@darranl @tadamski ^^^

**Comment by ropalka** [comment]
@fl4via ^^^

**Pull request merged**
