### PR TITLE
[WEJBHTTP-48] Close the connection when authentication failed

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/WEJBHTTP-48

### CODE REVIEW

**Comment by gaol** [comment]
@tadamski could you please review? thanks :)

**Review by tadamski — COMMENTED** [review]
@gaol I believe it would be better to just provide the tests with the required property. I have provided alternative fix in the following PR:
https://github.com/wildfly/wildfly/pull/13736
with the fix applied the hang is prevented

**Comment by gaol** [comment]
@tadamski will it lead connection leak if we don't close it in this case?

**Review by tadamski — APPROVED** [review]

**Comment by tadamski** [comment]
@fl4via would you be able to do a release with this change?

**Comment by fl4via** [comment]
Sure,@tadamski

**Comment by tadamski** [comment]
@fl4via  thanks!

**Pull request merged**
